@startuml Reto04_dObjeto
object "Jugador 1" as jv1{
    nombre = Mauricio Marquina
    telefono = 04129392137
    direccion = El paraiso
    numero = 5
    posicion = delantero central
    capitan = true
}

object "Jugador 2" as jv2{
    nombre = Mariangel Gomez
    telefono = 04241444778
    direccion = Av. Libertador
    numero = 4
    posicion = Libero 
    capitan = false
}

object "Jugador 3" as jv3{
    nombre = Gabriel Conde
    telefono = 04142105891
    direccion = Fuerte tiuna
    numero = 2
    posicion = Zaguero izquierdo
    capitan = false
}

object "Jugador 4" as jv4{
    nombre = Jharold Panza
    telefono = 04120998501
    direccion = Montalban
    numero = 16
    posicion = Zaguero derecho
    capitan = false
}

object "Jugador 5" as jv5{
    nombre = Migdalia Nogales
    telefono = 04142540264
    direccion = Andres Bello
    numero = 10
    posicion = delantero izquierdo
    capitan = false
}

object "Jugador 6" as jv6{
    nombre = Mauricio Gonzalez
    telefono = 04242539764
    direccion = Av. Baralt
    numero = 6
    posicion = Zaguero derecho
    capitan = false
}

object "Entrenador" as ev{
    nombre = Samuel Romero
    telefono = 04241056879
    direccion = Los jardines
    nivel_acreditacion= 4
    anos_exp= 10
}

object "Equipo 01" as equiV{
    nombre = Venezuela
}

object "Juego" as juego{
    localidad = Chile
    puntuacion = 5 - 3
}

object "Equipo 02" as equiC{
    nombre = Colombia
}

object "Jugador 1" as jc1{
    nombre = Daniel Genova
    telefono = 04142578994
    direccion = Bogota
    numero = 8
    posicion = delantero central
    capitan = false
}

object "Jugador 2" as jc2{
    nombre = Luis Rodriguez
    telefono = 04241734981
    direccion = Bogota
    numero = 9
    posicion = delantero izquierdo
    capitan = false
}

object "Jugador 3" as jc3{
    nombre = Josue Fernandez
    telefono = 04242024989
    direccion = Cali
    numero = 4
    posicion = Libero
    capitan = true
}


object "Jugador 4" as jc4{
    nombre = Julio Gutierrez
    telefono = 04263145861
    direccion = Barranquilla
    numero = 12
    posicion = delantero derecho
    capitan = false
}

object "Jugador 5" as jc5{
    nombre = Kenneth Fung
    telefono = 04242955413
    direccion = Bogota
    numero = 10
    posicion = Zaguero izquierdo
    capitan = false
}


object "Jugador 6" as jc6{
    nombre = Andres Macedo
    telefono = 04128161586
    direccion = Bogota
    numero = 2 
    posicion = zaguero derecho
    capitan = false
}

object "Entrenador" as ec{
    nombre = David Andrade
    telefono = 04124751165
    direccion = La Urdaneta
    nivel_acreditacion= 3
    anos_exp= 10
}


skinparam linetype ortho


 
equiV *-right- jv1 
equiV *-up- jv2
equiV *-up- jv3 
equiV *-up- jv4 
equiV *-up- jv5 
equiV *-up- jv6 


equiV -down- juego
juego -down- equiC
equiV o-left- ev
equiC o-right- ec



equiC *-down- jc1 
equiC *-down- jc2
equiC *-left- jc3 
equiC *-down- jc4 
equiC *-down- jc5 
equiC *-down- jc6 



@enduml
